{{- if not .Values.postgres.external }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "backstage.fullname" . }}-postgresql
  labels:
    {{- include "backstage.postgresql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
        {{- include "backstage.postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "backstage.fullname" . }}-postgresql
      creationTimestamp: null
      labels:
        {{- include "backstage.postgresql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- include "backstage.postgresql.adminSecretKey" . | indent 18 }}
          ports:
            - name: tcp-postgresql
              containerPort: 5432
              protocol: TCP
{{- if .Values.postgres.storage.enabled }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
{{- end }}
          terminationMessagePolicy: File
          image: "{{ .Values.postgres.image }}"
      serviceAccount: {{ include "backstage.serviceAccountName" . }}
{{- if .Values.postgres.storage.enabled }}
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: {{ include "backstage.fullname" . }}-postgresql
{{- end }}
  serviceName: {{ include "backstage.fullname" . }}-postgresql
{{- end }}
