{{- if .Values.postgres }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "backstage.postgresql.labels" . | nindent 4 }}
  name: "{{ include "backstage.fullname" . }}-postgresql"
stringData:
  {{- ( include "gen.postgres-password" . ) | indent 2 -}}
{{- end }}
