{{- if .Values.postgres }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.postgresql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.postgresql.labels" . | nindent 4 }}
stringData:
  {{- ( include "gen.postgres-password" . ) | indent 2 -}}
{{- end }}
